# Generated by Django 4.1.3 on 2022-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fantasy', 'fantasy'), ('journal', 'journal'), ('honor', 'honor'), ('light novel', 'light novel')], max_length=200, null=True),
        ),
    ]
