# Generated by Django 4.1.3 on 2022-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='templates/images/'),
        ),
    ]
