# Generated by Django 4.1.3 on 2022-11-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='image/123.jpg', null=True, upload_to='image'),
        ),
    ]
