# Generated by Django 4.1.3 on 2022-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_customer_order_book_digital_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fantasy', 'fantasy'), ('journal', 'journal'), ('honor', 'honor'), ('light novel', 'light novel'), ('E-book', 'E-book')], max_length=200, null=True),
        ),
    ]
